### ISSUE TITLE
TypeError: Cannot read property 'getClientRects' of null

### ISSUE THREAD

**Issue by dxvladislavvolkov** [clbond/angular-ssr#37]
getClientRects method is not implemented
You can see example [here](https://github.com/dxvladislavvolkov/angular-ssr-cli/tree/getClientRects)

**Comment by clbond** [comment]
OK, thank you for submitting your code along with the issue. There are several things wrong with what the code does and none of them involve `angular-ssr`:

```
var elem = document.getElementById("elem"),
    rects = elem.getClientRects();
```

This code is running in the app definition section, which means it runs before application initialization / bootstrap and before any rendering has ever happened. It is also running this code outside of the rendering context so `document` is likely to be wrong (basically just whatever `templateDocument` contains). So the `elem` element is never going to exist at this point. Therefore, `getElementById()` will always return null because the element doesn't exist. Which is why `getClientRects` cannot be called -- because the element itself is null.

Secondly, it does not make sense to try to query the size of an element in the context of a server-rendered application. You have no idea what the size of the screen is. It is impossible to calculate this value. This is the one DOM-related thing that you absolutely cannot do in SSR
